### ISSUE TITLE
在DialogFragment中使用圆角背景后面有黑边

### ISSUE THREAD

**Issue by Carlos2927** [fxc0719/RoundCornerLayout#2]
如图所示 但是如果父容器有非透明背景的话就不会存在这样的问题
![图片](https://user-images.githubusercontent.com/12493233/69527242-e178ce80-0fa6-11ea-8222-ffae83352b1d.png)
![图片](https://user-images.githubusercontent.com/12493233/69527379-21d84c80-0fa7-11ea-8571-a56a325adaf1.png)

**Comment by anatta-feng** [comment]
是的，这是因为他只是将自己及子 view 做了切割，对于他的父布局，需要父布局处理。设置为透明主题就没有这个问题了

**Comment by Carlos2927** [comment]
设置透明主题没用 我现在将dialog的背景设置为当前activiy界面截屏图片才解决了这个问题
